### ISSUE TITLE
Item hp is blank when pressing tab (in inventory)

### ISSUE THREAD

**Issue by danielwerg** [matias-kovero/BetterUI#1]
![UI bug](https://user-images.githubusercontent.com/35052399/113492376-74dce080-94c6-11eb-99fb-e2d98ca7bb58.png)

**Comment by danielwerg** [comment]
hmmm, fixed on server restart

**Comment by matias-kovero** [comment]
Missing durability bars is an bug on the core game, it might occur even if you don't use this mod. 
Restarting the game should fix it.
