### ISSUE TITLE
Unable to move items in edit mode.

### ISSUE THREAD

**Issue by sbeaudoin** [matias-kovero/BetterUI#6]
Maybe I did not understood something.  With v2.0.2, I press F7 to enter edit mode and I understood I can then use the mouse to select and move the item with the left mouse button, but the mouse move and mouse button make my characters react, not the editor.

Good work by the way (except this bug, or the instructions if it is not a bug ;-))

**Comment by matias-kovero** [comment]
You need to have your mouse usable when editing the UI.
The main issue is that if you don't have your mouse "free" you are unable to edit they UI, as the mouse moves the camera.

To control your mouse:
press ESC to open the menu then F7 to edit the UI
or
Open your inventory and then F7 to edit the UI.
